AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    API Gateway and Lambda for fastAPI-based DB API

Parameters:
  NetworkStack:
    Type: "String"
    Description: "Network stack to apply to."
  MySecurityGroupID:
    Type: "String"
    Description: "Security group ID."

Resources:
    DBAPILambda:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ApiEvent:
                    Properties:
                        RestApiId:
                            Ref: DBAPILambdaGateway
                        Path: /{proxy+}
                        Method: ANY
                    Type: Api
            FunctionName: fastapi-db-api-lambda
            CodeUri: ../source/
            Handler: db_api.main.handler
            Runtime: python3.8
            Timeout: 300 # timeout of your lambda function
            MemorySize: 128 # memory size of your lambda function
            Description: Lambda for fastAPI-based DB API
            # other options, see ->
            # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html#sam-specification-template-anatomy-globals-supported-resources-and-properties
            Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LambdaDBAPIExecution
            VpcConfig:
                SecurityGroupIds:
                    - !Sub ${MySecurityGroupID}
                SubnetIds:
                    - Fn::ImportValue:
                        !Sub ${NetworkStack}-DmzSubnetAId
                    - Fn::ImportValue:
                        !Sub ${NetworkStack}-DmzSubnetBId
                    - Fn::ImportValue:
                        !Sub ${NetworkStack}-DmzSubnetCId
            Tags:
                'Scope': 'public'
                'Purpose': 'API'
                'Service': 'knowledge'


    DBAPILambdaGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: dev
            OpenApiVersion: '3.0.0'
