"""Add entities and entity_mentions

Revision ID: 184607398420
Revises: 04a5bea10ab5
Create Date: 2020-10-15 08:49:25.084547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "184607398420"
down_revision = "04a5bea10ab5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("preferred_name", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=True),
        sa.Column(
            "synonyms", postgresql.ARRAY(sa.String(), dimensions=1), nullable=True
        ),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("modified_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entities_id"), "entities", ["id"], unique=False)
    op.create_index(
        op.f("ix_entities_modified_date"), "entities", ["modified_date"], unique=False
    )
    op.create_index(
        op.f("ix_entities_preferred_name"), "entities", ["preferred_name"], unique=False
    )
    op.create_table(
        "entity_mentions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("document_section", sa.String(), nullable=True),
        sa.Column("start_char", sa.Integer(), nullable=True),
        sa.Column("end_char", sa.Integer(), nullable=True),
        sa.Column("start_token", sa.Integer(), nullable=True),
        sa.Column("end_token", sa.Integer(), nullable=True),
        sa.Column("modified_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entity_mentions_document_id"),
        "entity_mentions",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_mentions_entity_id"),
        "entity_mentions",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_mentions_id"), "entity_mentions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_entity_mentions_modified_date"),
        "entity_mentions",
        ["modified_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_entity_mentions_modified_date"), table_name="entity_mentions"
    )
    op.drop_index(op.f("ix_entity_mentions_id"), table_name="entity_mentions")
    op.drop_index(op.f("ix_entity_mentions_entity_id"), table_name="entity_mentions")
    op.drop_index(op.f("ix_entity_mentions_document_id"), table_name="entity_mentions")
    op.drop_table("entity_mentions")
    op.drop_index(op.f("ix_entities_preferred_name"), table_name="entities")
    op.drop_index(op.f("ix_entities_modified_date"), table_name="entities")
    op.drop_index(op.f("ix_entities_id"), table_name="entities")
    op.drop_table("entities")
    # ### end Alembic commands ###
