"""Initial migration

Revision ID: 9d89078eb639
Revises:
Create Date: 2020-10-22 20:37:03.138551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d89078eb639"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entity_mentions", sa.Column("source", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_entity_mentions_source"), "entity_mentions", ["source"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entity_mentions_source"), table_name="entity_mentions")
    op.drop_column("entity_mentions", "source")
    # ### end Alembic commands ###
